#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -Werror
obj-y += st7701s_hsd50_fsd_lfwvga.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc



