#
# Makefile for misc devices that really don't fit anywhere else.
#
ccflags-y += -Werror
obj-y += ili9806e_hsd50_ykl_lfwvga.o
ccflags-$(CONFIG_MTK_LCM) += -I$(srctree)/drivers/misc/mediatek/lcm/inc



