ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/himax_852xES/
ccflags-y += -I$(srctree)/drivers/input/touchscreen/mediatek/
obj-$(CONFIG_TOUCHSCREEN_HIMAX852X)	+= himax_852xES.o himax_platform.o

