/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6 for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep  3 09:01:47 2018
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H


#define AUXADC_TEMPERATURE_CHANNEL     0
#define AUXADC_TEMPERATURE1_CHANNEL     1
#define AUXADC_ADC_FDD_RF_PARAMS_DYNAMIC_CUSTOM_CH_CHANNEL     12


#endif //_CUST_AUXADC_TOOL_H


