/*
 * Generated by MTK SP Drv_CodeGen Version 03.13.6  for MT6753. Copyright MediaTek Inc. (C) 2013.
 * Mon Sep  3 09:01:47 2018
 * Do Not Modify the File.
 */



#include <linux/types.h>
#include <mach/mt_typedefs.h>
#include <mach/upmu_common.h>
#include <mach/upmu_hw.h>
#include <mach/mt_pm_ldo.h>


void pmu_drv_tool_customization_init(void)
{
    pmic_set_register_value(PMIC_RG_VTCXO_1_EN,1);


    pmic_set_register_value(PMIC_RG_VSIM2_EN,1);


}




